jobs:
  test:
    executor:
      name: node/default
      tag: '14.5'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test-backend
          name: Run yarn test-backend
orbs:
  node: circleci/node@4.1.0
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test