jobs:
  test:
    executor:
      name: node/default
      tag: "14.5"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test-backend
          name: Run yarn test-backend
      - codecov/upload:
          file: packages/backend/coverage/coverage-final.json
          flags: backend
orbs:
  node: circleci/node@4.5.1
  codecov: codecov/codecov@1.0.2
  cypress: cypress-io/cypress@1
commands:
  front-end-report-coverage:
    description: |
      Send frontend end report coverage to Codecov.
    steps:
      - codecov/upload:
          file: coverage/coverage-final.json     
          flags: fontend
version: 2.1
workflows:
  test_fontend: 
    jobs:
      - cypress/install:
          executor: cypress/base-14-7-0
          yarn: true
      - cypress/run:
          executor: cypress/base-14-7-0
          requires:
            - cypress/install
          yarn: true
          parallel: true
          parallelism: 4
          record: true
          wait-on: http-get://localhost:3000/
          start: yarn start:e2e # start server before running tests
          post-steps:
            - front-end-report-coverage:
  test_my_app:
    jobs:
      - test
 